import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  root: { flex: 1, flexDirection: 'row', backgroundColor: '#0a0d14' }, workspace: { flex: 1 }, sidebar: { width: 320, backgroundColor: '#111622', borderRightWidth: 1, borderColor: '#283244' },
  brand: { height: 70, paddingHorizontal: 21, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1, borderColor: '#273042' }, brandIcon: { backgroundColor: '#ec738a', padding: 8, borderRadius: 7 }, brandTitle: { color: '#dce4f3', fontSize: 15, fontWeight: '700' }, sidebarFooter: { padding: 16, color: '#6f819e', fontSize: 10 },
  topbar: { height: 57, backgroundColor: '#0d121c', borderBottomWidth: 1, borderColor: '#222b3b', flexDirection: 'row', gap: 8, alignItems: 'center', paddingHorizontal: 13 }, mobileTitle: { flex: 1 }, title: { fontSize: 13, fontWeight: '700', color: '#dce4f3' }, subtitle: { color: '#8091ad', fontSize: 9, marginTop: 3 },
  directions: { flexDirection: 'row', padding: 2, gap: 2, borderWidth: 1, borderColor: '#303d54', borderRadius: 5, backgroundColor: '#161d29' }, direction: { minHeight: 31, paddingHorizontal: 7, borderRadius: 3, justifyContent: 'center' }, directionText: { color: '#8495b2', fontSize: 10 }, pip: { marginLeft: 'auto', flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 5, backgroundColor: '#d97489', paddingHorizontal: 9, minHeight: 33 }, pipText: { color: 'white', fontSize: 10, fontWeight: '600' }, badge: { fontSize: 10, color: '#a4c1ef', backgroundColor: '#14243b', padding: 7, borderRadius: 4 },
  stage: { flex: 1, overflow: 'hidden' }, stageHint: { position: 'absolute', left: 12, top: 12, fontSize: 9, color: '#70809a' }, hud: { position: 'absolute', right: 12, top: 43, padding: 7, backgroundColor: '#0d131db8', borderRadius: 5, borderWidth: 1, borderColor: '#3e4e69b8', alignItems: 'flex-end', gap: 3 }, fps: { fontSize: 13, color: '#dce9ff', fontWeight: '700', fontVariant: ['tabular-nums'] }, hudText: { color: '#90a2bf', fontSize: 9, fontVariant: ['tabular-nums'] },
  toast: { position: 'absolute', left: 12, bottom: 14, maxWidth: '94%', paddingVertical: 7, paddingHorizontal: 9, borderWidth: 1, borderColor: '#3e4e69bf', backgroundColor: '#0d131dc2', borderRadius: 5, flexDirection: 'row', gap: 8, alignItems: 'center' }, toastText: { fontSize: 10, color: '#cbd8ed', flexShrink: 1 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#52c993' },
  welcome: { ...StyleSheet.absoluteFill, alignItems: 'center', justifyContent: 'center', gap: 12 }, welcomeTitle: { fontSize: 19, color: '#dce4f3', fontWeight: '600' }, muted: { color: '#8090ad', fontSize: 11 },
  dock: { minHeight: 66, flexDirection: 'row', paddingTop: 7, borderTopWidth: 1, borderColor: '#293449', backgroundColor: '#101622' }, dockButton: { flex: 1, minHeight: 50, alignItems: 'center', justifyContent: 'center', gap: 5 }, dockText: { fontSize: 10, color: '#91a0ba' },
  backdrop: { ...StyleSheet.absoluteFill, backgroundColor: '#0000007a', justifyContent: 'flex-end' }, sheet: { backgroundColor: '#111826', borderWidth: 1, borderBottomWidth: 0, borderColor: '#334058', borderTopLeftRadius: 8, borderTopRightRadius: 8 }, sheetHead: { height: 40, alignItems: 'center', justifyContent: 'center' }, grabber: { width: 32, height: 3, borderRadius: 4, backgroundColor: '#53617a' }, close: { position: 'absolute', right: 12, padding: 10 },
  section: { paddingTop: 15, paddingHorizontal: 18 }, sectionLabel: { fontSize: 10, fontWeight: '700', color: '#8090ad', marginBottom: 10 }, modelCard: { minHeight: 56, borderWidth: 1, borderColor: '#2d3950', backgroundColor: '#171e2c', borderRadius: 6, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 10 }, modelMark: { width: 36, height: 36, borderRadius: 5, backgroundColor: '#f0c4cd', alignItems: 'center', justifyContent: 'center' }, markText: { fontFamily: 'Georgia', fontSize: 20, fontStyle: 'italic', color: '#172130' }, modelName: { color: '#dce4f3', fontSize: 13, fontWeight: '600' }, modelOutfit: { color: '#8798b4', fontSize: 10, marginTop: 3 },
  row: { flexDirection: 'row', gap: 7, paddingTop: 8 }, action: { flex: 1, minHeight: 34, borderWidth: 1, borderColor: '#344159', backgroundColor: '#1a2231', borderRadius: 5, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8, gap: 5 }, compact: { flex: 0, width: 36, minWidth: 36 }, actionText: { color: '#bbc8da', fontSize: 11, flexShrink: 1 }, selected: { borderColor: '#bc667c', backgroundColor: '#382530' }, selectedText: { color: '#ffd3dc' },
  range: { minHeight: 35, flexDirection: 'row', gap: 6, alignItems: 'center' }, rangeLabel: { width: 55, fontSize: 11, color: '#9aa9c2' }, rangeValue: { width: 40, textAlign: 'right', fontSize: 10, color: '#d9e6fa', fontVariant: ['tabular-nums'] }, slider: { flex: 1, height: 32 },
  segments: { flexDirection: 'row', padding: 3, gap: 3, marginTop: 9, borderWidth: 1, borderColor: '#303c51', borderRadius: 5, backgroundColor: '#171e2c' }, segment: { flex: 1, minHeight: 31, justifyContent: 'center', alignItems: 'center', borderRadius: 3 }, segmentActive: { backgroundColor: '#37455f' }, segmentText: { fontSize: 11, color: '#8090ad' }, activeText: { color: '#f2f6ff' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingTop: 12 }, gridHalf: { width: '48.5%' }, gridThird: { width: '31.8%' }, empty: { color: '#8090ad', fontSize: 11, paddingVertical: 12 }, selectionList: { gap: 5, paddingTop: 7 },
});
